  - name: cart services
    hosts: cart
    become: yes
    tasks: 
      - name: disabled and enabled node js
        ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

      - name: install nodejs
        ansible.builtin.dnf:
          name: nodejs
          state: present

      - name: user add
        ansible.builtin.user:
          name: roboshop

      - name: remove the app
        ansible.builtin.file:
          name: /app
          state: absent

      - name: add directory
        ansible.builtin.file:
          name: /app
          state: directory

      - name: download the file
        ansible.builtin.get_url:
          url: https://roboshop-builds.s3.amazonaws.com/cart.zip
          dest: /tmp

      - name: unzip the file
        ansible.builtin.unarchive:
          src: /tmp/cart.zip
          dest: /app
          remote_src: yes
      
      - name: install dependices
        ansible.builtin.command: npm install
        args:
          chdir: /app
      
      - name: copied the configuration
        ansible.builtin.copy:
          src: cart.service
          dest: /etc/systemd/system/cart.service

      - name: Daemon reload
        ansible.builtin.systemd_service:
          daemon_reload: true

      - name: enable and restart system
        ansible.builtin.service:
          name: cart
          state: restarted
          enabled: yes