  - name: catalogue
    hosts: catalogue
    become: yes
    tasks:
    - name: disabled and enabled nodejs-18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: useradd
      ansible.builtin.user:
        name: roboshop

    - name: remove the app directory
      ansible.builtin.file:
        path: /app
        state: absent 

    - name: directory add
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download zip filed
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: unziping the file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: installing the dependices
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: daemon reload
      ansible.builtin.systemd_service:
      daemon_reload: true

    - name: start catalogue
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: mongodb
      ansible.builtin.copy:
        src: mongodn.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present
    
    - name: get categories count
      ansible.builtin.command: mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: load catagories data
      ansible.builtin.command: mongo --host mongodb.vs-devops.online < /app/schema/catalogue.js
      when: product_count.stout == "0"

    - name: start and enable catalogue
      ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

       

