  - name: mongodb
    hosts: mongodb 
    become: yes
    tasks:

      - name: copy mongod
        ansible.builtin.copy:
          src: mongodb.repo
          dest: /etc/yum.repos.d/mongodb.repo

      - name: mongodb install
        ansible.builtin.package:
          name: mongodb-org
          state: present

      - name: mongodb start
        ansible.builtin.service:
          name: mongod
          state: started
          enabled: yes
      - name: mongodb conf
        ansible.builtin.replace:
          path: /etc/mongod.conf
          regexp: '127.0.0.1'
          replace: '0.0.0.0'
      
      - name: mongodb restart
        ansible.builtin.service:
          name: mongod
          state: restart
