  - name: rabbit
    hosts: rabbit
    become: yes
    tasks:
      - name: installing script from vendor
        ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash ; curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

      - name: install packages 
        ansible.builtin.package:
          name: rabbitmq-server
          state: present

      - name: enabled and restarted
        ansible.builtin.service:
          name: rabbit
          state: restarted
          enabled: yes
      
      - name: setting user and password
        ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"